/** 主なオープニングの日本語名（D38）。キーは lichess-org/chess-openings の英語名の先頭部分。 */
export const JA_FAMILY_NAMES: Record<string, string> = {
  "Alekhine Defense": "アリョーヒン・ディフェンス",
  "Benoni Defense": "ベノニ・ディフェンス",
  "Bird Opening": "バード・オープニング",
  "Bishop's Opening": "ビショップス・オープニング",
  "Bogo-Indian Defense": "ボゴ・インディアン・ディフェンス",
  "Caro-Kann Defense": "カロ・カン・ディフェンス",
  "Center Game": "センター・ゲーム",
  "Dutch Defense": "ダッチ・ディフェンス",
  "English Opening": "イングリッシュ・オープニング",
  "Four Knights Game": "フォー・ナイツ・ゲーム",
  "French Defense": "フレンチ・ディフェンス",
  "Grünfeld Defense": "グリュンフェルド・ディフェンス",
  "Indian Defense": "インディアン・ディフェンス",
  "Italian Game": "イタリアン・ゲーム",
  "King's Gambit": "キングズ・ギャンビット",
  "King's Gambit Accepted": "キングズ・ギャンビット・アクセプテッド",
  "King's Gambit Declined": "キングズ・ギャンビット・ディクラインド",
  "King's Indian Attack": "キングズ・インディアン・アタック",
  "King's Indian Defense": "キングズ・インディアン・ディフェンス",
  "King's Pawn Game": "キングズ・ポーン・ゲーム",
  "London System": "ロンドン・システム",
  "Modern Defense": "モダン・ディフェンス",
  "Nimzo-Indian Defense": "ニムゾ・インディアン・ディフェンス",
  "Nimzo-Larsen Attack": "ニムゾ・ラーセン・アタック",
  "Petrov's Defense": "ペトロフ・ディフェンス",
  "Philidor Defense": "フィリドール・ディフェンス",
  "Pirc Defense": "ピルツ・ディフェンス",
  "Ponziani Opening": "ポンツィアーニ・オープニング",
  "Queen's Gambit Accepted": "クイーンズ・ギャンビット・アクセプテッド",
  "Queen's Gambit Declined": "クイーンズ・ギャンビット・ディクラインド",
  "Queen's Gambit": "クイーンズ・ギャンビット",
  "Queen's Indian Defense": "クイーンズ・インディアン・ディフェンス",
  "Queen's Pawn Game": "クイーンズ・ポーン・ゲーム",
  "Réti Opening": "レティ・オープニング",
  "Ruy Lopez": "ルイ・ロペス",
  "Scandinavian Defense": "スカンジナビアン・ディフェンス",
  "Scotch Game": "スコッチ・ゲーム",
  "Semi-Slav Defense": "セミ・スラブ・ディフェンス",
  "Sicilian Defense": "シシリアン・ディフェンス",
  "Slav Defense": "スラブ・ディフェンス",
  "Three Knights Opening": "スリー・ナイツ・オープニング",
  "Two Knights Defense": "ツー・ナイツ・ディフェンス",
  "Van't Kruijs Opening": "ファント・クライス・オープニング",
  "Vienna Game": "ウィーン・ゲーム",
  "Zukertort Opening": "ツケルトート・オープニング",
};
